---
become_override: false
ocp_username: user-redhat.com
silent: false
tmp_dir: /tmp/{{ guid }}
tmp_kubeconfig: "{{ tmp_dir }}/.kube/config"
ocp4_workload_gitops_aap_instances:
  controller: true
  hub: true
ocp4_workload_gitops_aap_repo: https://github.com/redhat-gpte-devopsautomation/aap2-gitops