## Automation Controller
- name: Set up automation controller
  when: ocp4_workload_gitops_aap_enable_instances.controller |bool
  block:
  - name: Set up automation controller - argocd
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-multiuser-controller.yml.j2' ) | from_yaml }}"

## Automation Hub
- name: Set up automation hub
  when: ocp4_workload_gitops_aap_enable_instances.hub |bool
  block:
  - name: Set up automation hub - argocd
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-multiuser-hub.yml.j2' ) | from_yaml }}"
