---
- name: Generate AAP admin password if no password specified
  when: ocp4_workload_gitops_aap_admin_password | default("") | length == 0
  ansible.builtin.set_fact:
    ocp4_workload_gitops_aap_admin_password: >-
      {{ lookup('password', '/dev/null length={{ ocp4_workload_gitops_aap_password_length }} chars=ascii_letters,digits') }}

- name: Determine Wildcard Domain
  kubernetes.core.k8s_info:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
  register: r_ingress_controller

- name: Set variables
  ansible.builtin.set_fact:
    _ocp4_workload_gitops_aap_wildcard_domain: "{{ r_ingress_controller.resources[0].status.domain }}"
    
## Automation Controller
- name: Set up automation controller
  when: ocp4_workload_gitops_aap_enable_instances.controller |bool
  block:
  - name: Set up automation controller - argocd
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-multiuser-controller.yaml.j2' ) | from_yaml }}"

  - name: Save code server information for each user
    agnosticd_user_info:
      user: "{{ ocp4_workload_gitops_aap_multiuser_username_base }}{{ n }}"
      data:
        ac_controller_url: >-
          https://{{ocp4_workload_gitops_aap_controller_name}}-{{
          ocp4_workload_gitops_aap_multiuser_namespace_base }}-{{
          ocp4_workload_gitops_aap_multiuser_username_base }}{{n}}.{{
          _ocp4_workload_gitops_aap_wildcard_domain}}
    loop: "{{ range(1, 1 + ocp4_workload_gitops_aap_multiuser_num_users | int) | list }}"
    loop_control:
      loop_var: n
      label: "{{ ocp4_workload_gitops_aap_multiuser_username_base }}{{ n }}"

## Automation Hub
- name: Set up automation hub
  when: ocp4_workload_gitops_aap_enable_instances.hub |bool
  block:
  - name: Set up automation hub - argocd
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-multiuser-hub.yaml.j2' ) | from_yaml }}"

  - name: Save code server information for each user
    agnosticd_user_info:
      user: "{{ ocp4_workload_gitops_aap_multiuser_username_base }}{{ n }}"
      data:
        ac_controller_url: >-
          https://{{ocp4_workload_gitops_aap_hub_name}}-{{
          ocp4_workload_gitops_aap_multiuser_namespace_base }}-{{
          ocp4_workload_gitops_aap_multiuser_username_base }}{{n}}.{{
          _ocp4_workload_gitops_aap_wildcard_domain}}
    loop: "{{ range(1, 1 + ocp4_workload_gitops_aap_multiuser_num_users | int) | list }}"
    loop_control:
      loop_var: n
      label: "{{ ocp4_workload_gitops_aap_multiuser_username_base }}{{ n }}"