## Automation Controller
- name: Set up automation controller
  when: ocp4_workload_gitops_aap_enable_instances.controller |bool
  block:
  - name: Set up automation controller - argocd
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-controller.yaml.j2' ) | from_yaml }}"

  - name: Retrieve created controller route
    k8s_facts:
      api_version: "route.openshift.io/v1"
      kind: Route
      name: controller
      namespace: ansible-automation-platform
    register: r_ac_route
    until: r_ac_route.resources[0].spec.host is defined
    retries: 300
    delay: 30

  - name: Retrieve aap secret
    k8s_facts:
      api_version: "v1"
      kind: Secret
      name: controller-admin-password
      namespace: ansible-automation-platform
    register: r_ac_secret
    until:
    - r_ac_secret.resources is defined
    - r_ac_secret.resources | length > 0
    - r_ac_secret.resources[0].data.password
    retries: 300
    delay: 30

  - name: Get automation_controller route hostname
    set_fact:
      automation_controller_hostname: "{{ r_ac_route.resources[0].spec.host }}"
      automation_controller_admin_password: "{{ r_ac_secret.resources[0].data.password |string |b64decode }}"

  - name: wait for automation_controller to be running
    uri:
      url: http://{{ automation_controller_hostname }}/api/v2/ping/
      status_code: 200
    register: result
    until: result.json.version is defined
    retries: 300
    delay: 30

  - name: Pause for 5 minutes for AC to be ready
    pause:
      minutes: 5

  - name: Display version
    debug:
      msg: "{{ result.json.version }}"
    when: not silent | bool

  - name: Store Controller Access information
    agnosticd_user_info:
      user: admin
      data:
        ac_web_url: "https://{{ automation_controller_hostname }}"
        ac_user: "admin"
        ac_password: "{{ automation_controller_admin_password }}"

## Automation Hub
- name: Set up automation hub
  when: ocp4_workload_gitops_aap_enable_instances.hub |bool
  block:
  - name: Set up automation hub - argocd
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-hub.yaml.j2' ) | from_yaml }}"

  - name: Retrieve created hub route
    k8s_facts:
      api_version: "route.openshift.io/v1"
      kind: Route
      name: hub
      namespace: ansible-automation-platform
    register: r_ah_route
    until: r_ah_route.resources[0].spec.host is defined
    retries: 300
    delay: 30

  - name: Retrieve hub secret
    k8s_facts:
      api_version: "v1"
      kind: Secret
      name: hub-admin-password
      namespace: ansible-automation-platform
    register: r_ah_secret
    until:
    - r_ah_secret.resources is defined
    - r_ah_secret.resources | length > 0
    - r_ah_secret.resources[0].data.password
    retries: 300
    delay: 30

  - name: Get automation_hub route hostname
    set_fact:
      automation_hub_hostname: "{{ r_ah_route.resources[0].spec.host }}"
      automation_hub_admin_password: "{{ r_ah_secret.resources[0].data.password |string |b64decode }}"

  - name: Store Hub Access information
    agnosticd_user_info:
      user: admin
      data:
        ah_web_url: "https://{{ automation_hub_hostname }}"
        ah_user: "admin"
        ah_password: "{{ automation_hub_admin_password }}"