---
# Implement your Workload deployment tasks here
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- environment:
    KUBECONFIG: "{{ tmp_kubeconfig }}"
  block:
  - name: Create AAP Operator Argocd Application
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template',  'aap-operator.yaml.j2' ) | from_yaml }}"

  - name: Deploy AAP for Single User
    when: not ocp4_workload_gitops_aap_multiuser_install | bool
    include_tasks: singleuser_deployer.yml

  - name: Deploy AAP for Single User
    when: ocp4_workload_gitops_aap_multiuser_install | bool
    include_tasks: multiuser_deployer.yml

  - name: Openshift Gitops server info
    include_tasks: argocd_info.yml

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent | bool